replicaCount: 1

image:
  repository: ghcr.io/narayanangourav/cuba-web
  tag: "2026080902"
  pullPolicy: Always

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

containerPort: 8080

service:
  type: ClusterIP
  port: 80

probes:
  readiness:
    path: /healthz
    initialDelaySeconds: 2
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 3

  liveness:
    path: /healthz
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3

resources:
  requests:
    cpu: 25m
    memory: 32Mi
  limits:
    cpu: 250m
    memory: 128Mi

revisionHistoryLimit: 3
